"""
Database Protocols module.
All protocols related to CRUD operations with databases should be defined here.
"""

from src.protocol.internal.database import allocation, form_field, mixin, room, user
from src.protocol.internal.database.allocation import (
    AllocationDatabaseProtocol,
    CreateAllocation,
    CreateClosedAllocation,
    CreateCreatedAllocation,
    CreateCreatingAllocation,
    CreateFailedAllocation,
    CreateOpenAllocation,
    CreateRoomedAllocation,
    CreateRoomingAllocation,
    DeleteAllocation,
    ReadAllocation,
    UpdateAllocation,
)
from src.protocol.internal.database.form_field import (
    CreateAnswer,
    CreateChoiceAnswer,
    CreateChoiceFormField,
    CreateFormField,
    CreateTextAnswer,
    CreateTextFormField,
    DeleteAnswer,
    DeleteFormField,
    FormFieldDatabaseProtocol,
    ReadAnswer,
    ReadFormField,
    UpdateAnswer,
    UpdateChoiceAnswer,
    UpdateChoiceFormField,
    UpdateChoiceOption,
    UpdateFormField,
    UpdateTextAnswer,
    UpdateTextFormField,
)
from src.protocol.internal.database.mixin import ExcludeFieldMixin
from src.protocol.internal.database.room import (
    CreateRoom,
    DeleteRoom,
    ReadRoom,
    RoomDatabaseProtocol,
    UpdateRoom,
)
from src.protocol.internal.database.user import (
    CreateUser,
    DeleteUser,
    ReadUser,
    UpdateUser,
    UserDatabaseProtocol,
)

__all__ = [
    allocation,
    form_field,
    mixin,
    room,
    user,
    CreateCreatingAllocation,
    CreateCreatedAllocation,
    CreateOpenAllocation,
    CreateRoomingAllocation,
    CreateRoomedAllocation,
    CreateClosedAllocation,
    CreateFailedAllocation,
    CreateAllocation,
    ReadAllocation,
    UpdateAllocation,
    DeleteAllocation,
    AllocationDatabaseProtocol,
    CreateTextFormField,
    CreateChoiceFormField,
    CreateFormField,
    CreateFormField,
    ReadFormField,
    UpdateTextFormField,
    UpdateChoiceOption,
    UpdateChoiceFormField,
    UpdateFormField,
    DeleteFormField,
    CreateTextAnswer,
    CreateChoiceAnswer,
    CreateAnswer,
    ReadAnswer,
    UpdateTextAnswer,
    UpdateChoiceAnswer,
    UpdateAnswer,
    DeleteAnswer,
    FormFieldDatabaseProtocol,
    ExcludeFieldMixin,
    CreateRoom,
    ReadRoom,
    UpdateRoom,
    DeleteRoom,
    RoomDatabaseProtocol,
    CreateUser,
    ReadUser,
    UpdateUser,
    DeleteUser,
    UserDatabaseProtocol,
]
