"""
Database Protocols module.
All protocols related to CRUD operations with databases should be defined here.
"""

from src.protocol.internal.database import allocation, form_field, mixin, room, user

__all__ = [
    allocation,
    form_field,
    mixin,
    room,
    user,
    allocation.CreateCreatingAllocation,
    allocation.CreateCreatedAllocation,
    allocation.CreateOpenAllocation,
    allocation.CreateRoomingAllocation,
    allocation.CreateRoomedAllocation,
    allocation.CreateClosedAllocation,
    allocation.CreateFailedAllocation,
    allocation.CreateAllocation,
    allocation.ReadAllocation,
    allocation.UpdateAllocation,
    allocation.DeleteAllocation,
    allocation.AllocationDatabaseProtocol,
    form_field.CreateTextFormField,
    form_field.CreateChoiceFormField,
    form_field.CreateFormField,
    form_field.CreateFormField,
    form_field.ReadFormField,
    form_field.UpdateTextFormField,
    form_field.UpdateChoiceOption,
    form_field.UpdateChoiceFormField,
    form_field.UpdateFormField,
    form_field.DeleteFormField,
    form_field.CreateTextAnswer,
    form_field.CreateChoiseAnswer,
    form_field.CreateAnswer,
    form_field.ReadAnswer,
    form_field.UpdateTextAnswer,
    form_field.UpdateChoiseAnswer,
    form_field.UpdateAnswer,
    form_field.DeleteAnswer,
    form_field.FormFieldDatabaseProtocol,
    mixin.ExcludeFieldMixin,
    room.CreateRoom,
    room.ReadRoom,
    room.UpdateRoom,
    room.DeleteRoom,
    room.RoomDatabaseProtocol,
    user.CreateUser,
    user.ReadUser,
    user.UpdateUser,
    user.DeleteUser,
    user.UserDatabaseProtocol,
]
