from src.domain.exception.base import DomainException


class ServiceException(DomainException): ...


class CreateUserException(ServiceException): ...


class ReadUserException(ServiceException): ...


class UpdateUserException(ServiceException): ...


class DeleteUserException(ServiceException): ...
