from src.domain.exception.base import DomainException


class ServiceException(DomainException): ...


class UserException(ServiceException): ...


class CreateUserException(UserException): ...


class ReadUserException(UserException): ...


class UpdateUserException(UserException): ...


class DeleteUserException(UserException): ...


class AllocationException(ServiceException): ...


class CreateAllocationException(AllocationException): ...


class ReadAllocationException(AllocationException): ...


class UpdateAllocationException(AllocationException): ...


class DeleteAllocationException(AllocationException): ...


class RoomException(ServiceException): ...


class CreateRoomException(RoomException): ...


class ReadRoomException(RoomException): ...


class UpdateRoomException(RoomException): ...


class DeleteRoomException(RoomException): ...


class FormFieldException(ServiceException): ...


class CreateFormFieldException(FormFieldException): ...


class ReadFormFieldException(FormFieldException): ...


class UpdateFormFieldException(FormFieldException): ...


class DeleteFormFieldException(FormFieldException): ...


class ParticipantException(ServiceException): ...


class CreateParticipantException(ParticipantException): ...


class ReadParticipantException(ParticipantException): ...


class UpdateParticipantException(ParticipantException): ...


class DeleteParticipantException(ParticipantException): ...


class PreferenceException(ServiceException): ...


class CreatePreferenceException(PreferenceException): ...


class ReadPreferenceException(PreferenceException): ...


class UpdatePreferenceException(PreferenceException): ...


class DeletePreferenceException(PreferenceException): ...
